### ISSUE TITLE
Android Studio Warning thrown for /Application/tests/AndroidManifest.xml

### ISSUE THREAD

**Issue by crow1170** [googlesamples/android-BasicNotifications#1]
I used this project from the Android Studio 'import sample' feature. It runs just fine, but I was also trying to test out Android Studio's version control integration. When I tried to commit this code (with no changes), the following error was generated:

```
Error:(37, 36) Cannot resolve symbol 'com.example.android.basicnotifications'
```

I realize that this may be beyond the scope of this project, but the surrounding comments did not help me understand the problem:

```
<!--
Specifies the instrumentation test runner used to run the tests.
-->
```

I thought maybe I could come here for help. I gather that this is supposed to point to an actual test, but no such test appears to be included in the repository.

**Comment by keyboardsurfer** [comment]
The target package name is correctly specified.
This message is being produced by a lint check.
You can safely ignore it in this case or locally suppress it by adding
`<!--suppress AndroidDomInspection -->`
before the opening `instrumentation` tag.
