### ISSUE TITLE
Please add repo description

### ISSUE THREAD

**Issue by dandv** [googlesamples/android-BasicNotifications#6]
![image](https://user-images.githubusercontent.com/33569/27247267-d1355198-52ab-11e7-9014-8c94629e86f3.png)

**Comment by rshivam08** [comment]
Hey @dandv  i would like to work on this issue. Please let me know if it is not yet solved..?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
