### ISSUE TITLE
Error Word -_-

### ISSUE THREAD

**Issue by vikingden8** [googlesamples/android-BasicNotifications#7]
Commononly should be Commonly under line 77 in MainActivity.java

**Comment by rshivam08** [comment]
Hey @vikingden8, i would like to work on this issue. Please let me know if it is not yet solved..?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
